workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'push'

image: python:3.9


stages:
  - test


before_script:
    - pip install sqlalchemy[mypy]
    - pip install -r requirements.txt
    - git clone https://github.com/python/mypy.git
    - cd mypy
    - pip install --upgrade .

unittest:
  stage: test
  script:
    - pytest test

mypy:
  stage: test
  script:
    - mypy src/

black:
  stage: test
  script:
    - black --diff --check src/

isort:
  stage: test
  script:
    - isort --check-only src/

flask8:
  stage: test
  script:
    - flake8 src/
